2022-11-19 17:36:49,310  INFO JPAService:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[] No results found
2022-11-19 17:36:49,332  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@:start:] Start action [0000001-221119014854194-oozie-root-W@:start:] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2022-11-19 17:36:49,332  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@:start:] [***0000001-221119014854194-oozie-root-W@:start:***]Action status=DONE
2022-11-19 17:36:49,332  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@:start:] [***0000001-221119014854194-oozie-root-W@:start:***]Action updated in DB!
2022-11-19 17:36:49,391  INFO JPAService:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@:start:] No results found
2022-11-19 17:36:49,409  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@:start:] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W@:start:
2022-11-19 17:36:49,409  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W
2022-11-19 17:36:49,435  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Start action [0000001-221119014854194-oozie-root-W@spark-3c85] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2022-11-19 17:36:51,902  INFO SparkActionExecutor:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] checking action, hadoop job ID [job_1668793721606_0001] status [RUNNING]
2022-11-19 17:36:51,904  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] [***0000001-221119014854194-oozie-root-W@spark-3c85***]Action status=RUNNING
2022-11-19 17:36:51,904  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] [***0000001-221119014854194-oozie-root-W@spark-3c85***]Action updated in DB!
2022-11-19 17:36:51,916  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W@spark-3c85
2022-11-19 17:37:18,852  INFO CallbackServlet:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] callback for action [0000001-221119014854194-oozie-root-W@spark-3c85]
2022-11-19 17:37:49,249  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:37:49,250  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:37:49,251  INFO ActionCheckXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Next Retry, Attempt Number [1] in [10,000] milliseconds
2022-11-19 17:38:29,628  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:38:29,629  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:38:29,629  INFO ActionCheckXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Next Retry, Attempt Number [2] in [10,000] milliseconds
2022-11-19 17:39:10,006  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:39:10,006  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:39:10,006  INFO ActionCheckXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Next Retry, Attempt Number [3] in [10,000] milliseconds
2022-11-19 17:39:50,368  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:39:50,368  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 30 more
2022-11-19 17:39:50,369  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exceeded max retry count [3]. Suspending Job
2022-11-19 17:39:50,369  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Suspending Workflow Job id=0000001-221119014854194-oozie-root-W
2022-11-20 19:33:14,153  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Start action [0000001-221119014854194-oozie-root-W@spark-3c85] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2022-11-20 19:33:14,655  INFO SparkActionExecutor:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] checking action, hadoop job ID [job_1668793721606_0005] status [RUNNING]
2022-11-20 19:33:14,656  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] [***0000001-221119014854194-oozie-root-W@spark-3c85***]Action status=RUNNING
2022-11-20 19:33:14,656  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] [***0000001-221119014854194-oozie-root-W@spark-3c85***]Action updated in DB!
2022-11-20 19:33:14,660  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W
2022-11-20 19:33:14,660  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W@spark-3c85
2022-11-20 19:33:34,638  INFO CallbackServlet:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] callback for action [0000001-221119014854194-oozie-root-W@spark-3c85]
2022-11-20 19:34:05,004  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:34:05,004  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:34:05,005  INFO ActionCheckXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Next Retry, Attempt Number [1] in [10,000] milliseconds
2022-11-20 19:34:09,499  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W
2022-11-20 19:34:45,371  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:34:45,372  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:34:45,372  INFO ActionCheckXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Next Retry, Attempt Number [2] in [10,000] milliseconds
2022-11-20 19:35:25,732  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:35:25,733  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:35:25,734  INFO ActionCheckXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Next Retry, Attempt Number [3] in [10,000] milliseconds
2022-11-20 19:36:06,110  WARN SparkActionExecutor:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception in check(). Message[java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
java.io.IOException: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:338)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 21 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:36:06,110  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exception while executing check(). Error Code [  JA006], Message[  JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused]
org.apache.oozie.action.ActionExecutorException:   JA006: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:457)
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:437)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1591)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:182)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From bigdata-cdh01.itcast.cn/192.168.59.140 to bigdata-cdh01.itcast.cn:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
	at org.apache.hadoop.ipc.Client.call(Client.java:1508)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy33.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:423)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:698)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:206)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:604)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:612)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:642)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.getRunningJob(JavaActionExecutor.java:1457)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.check(JavaActionExecutor.java:1480)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:648)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:744)
	at org.apache.hadoop.ipc.Client$Connection.access$3000(Client.java:396)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1557)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	... 29 more
2022-11-20 19:36:06,110  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Exceeded max retry count [3]. Suspending Job
2022-11-20 19:36:06,111  WARN ActionCheckXCommand:523 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Suspending Workflow Job id=0000001-221119014854194-oozie-root-W
2022-11-21 08:38:49,182  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] Start action [0000001-221119014854194-oozie-root-W@spark-3c85] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2022-11-21 08:38:49,747  INFO SparkActionExecutor:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] checking action, hadoop job ID [job_1668793721606_0011] status [RUNNING]
2022-11-21 08:38:49,749  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] [***0000001-221119014854194-oozie-root-W@spark-3c85***]Action status=RUNNING
2022-11-21 08:38:49,749  INFO ActionStartXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] [***0000001-221119014854194-oozie-root-W@spark-3c85***]Action updated in DB!
2022-11-21 08:38:49,753  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[root] GROUP[-] TOKEN[] APP[hue_wf_spark_yarn_pi] JOB[0000001-221119014854194-oozie-root-W] ACTION[] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W
2022-11-21 08:38:49,753  INFO WorkflowNotificationXCommand:520 - SERVER[bigdata-cdh01.itcast.cn] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[0000001-221119014854194-oozie-root-W] ACTION[0000001-221119014854194-oozie-root-W@spark-3c85] No Notification URL is defined. Therefore nothing to notify for job 0000001-221119014854194-oozie-root-W@spark-3c85